---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-watcher-sa
  namespace: hiro
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-watcher-clusterrole
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-watcher-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: pod-watcher-sa
  namespace: hiro
roleRef:
  kind: ClusterRole
  name: pod-watcher-clusterrole
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-server
  namespace: hiro
  labels:
    app: webhook-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook-server
  template:
    metadata:
      labels:
        app: webhook-server
    spec:
      serviceAccountName: pod-watcher-sa
      containers:
        - name: webhook-server
          image: workloadstealagent:alpha1
          imagePullPolicy: IfNotPresent
          env:
          - name: NATS_URL
            value: "demo.nats.io:4222"  
          - name: NATS_SUBJECT
            value: "WorkStealingPod"
          - name: WORK_LOAD_STEAL_LABLE
            value: "WorkLoadSteal"
          - name: IGNORE_NAMESPACES
            value: "default,kube-system,hiro"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8443
          volumeMounts:
            - name: tls-certs
              mountPath: /etc/certs
              readOnly: true
      volumes:
        - name: tls-certs
          secret:
            secretName: webhook-server-tls
