# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: validation-webhook-server
#   namespace: hiro
# spec:
#   selector:
#     app: webhook-server
#   ports:
#     - port: 443
#       targetPort: 8444
# ---
apiVersion: v1
kind: Service
metadata:
  name: mutation-webhook-server
  namespace: hiro
spec:
  selector:
    app: mutation-webhook-server
  ports:
    - port: 443
      targetPort: 8443
