apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: webhook-server
webhooks:
  - name: "webhook-server.hiro.svc"
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: In
          values: [ "myorgops" ]
    rules:
      - operations: [ "CREATE"]
        apiGroups: [ "apps" ]
        apiVersions: [ "v1" ]
        resources: [ "pods" ]
        scope: "Namespaced"
    clientConfig:
      service:
        namespace: hiro
        name: webhook-server
        path: "/validate"
      caBundle: <ENCODED_CA>
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 5
