apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: webhook-server
webhooks:
  - name: "webhook-server.hiro.svc"
    admissionReviewVersions: ["v1"]
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values: [ "default", "kube-system", "hiro" ]
    rules:
      - operations: [ "CREATE"]
        apiGroups: [ "" ]
        apiVersions: [ "v1" ]
        resources: [ "pods" ]
    clientConfig:
      service:
        namespace: hiro
        name: webhook-server
        path: "/validate"
      caBundle: <ENCODED_CA>
    sideEffects: None
    timeoutSeconds: 5
